version: '3.8'
services:
  gpt-archive:
    platform: linux/amd64
    image: 849441246713.dkr.ecr.ap-northeast-2.amazonaws.com/chrome-extension-frontend-ecr:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: gpt-archive-fe
    environment:
      - NODE_ENV=production
      - PROJECT_NAME=gpt-archive-fe
      - NEXT_SHARP_PATH=/app/node_modules/sharp
    ports:
      - '3000:3000'
