import type { Metadata } from "next";
import { Edu_VIC_WA_NT_Beginner, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { cn } from "@/lib/utils";

// const inter = Font.Inter({ subsets: ["latin"] });
const edu_VIC_WA_NT_Beginner = Edu_VIC_WA_NT_Beginner({
  subsets: ["latin"],
  variable: "--Edu_VIC_WA_NT_Beginner",
});

const noto_Sans_Korean = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={cn(
          noto_Sans_Korean.className,
          edu_VIC_WA_NT_Beginner.variable
        )}
      >
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
