import type { Metadata } from 'next'
import { Edu_VIC_WA_NT_Beginner, Noto_Sans_KR } from 'next/font/google'
import './globals.css'
import ReactQueryProvider from '@/components/providers/ReactQueryProvider'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/ThemeProvider'
import AuthContextProvider from '@/components/providers/AuthContextProvider'
import MainNav from '@/components/ui/main-nav'

// const inter = Font.Inter({ subsets: ["latin"] });
const LogoFont = Edu_VIC_WA_NT_Beginner({
  subsets: ['latin'],
  variable: '--Edu_VIC_WA_NT_Beginner',
})

const NotoSansKr = Noto_Sans_KR({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={cn(
          NotoSansKr.className,
          LogoFont.variable,
          'bg-[#F8F9FA] text-[#333] dark:bg-[#101010] dark:text-white',
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ReactQueryProvider>
            <AuthContextProvider>
              <main className="mx-auto flex h-full min-h-screen w-full flex-col items-center">
                <MainNav />
                {children}
                {modal}
              </main>
            </AuthContextProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
